### ISSUE TITLE
Start publishing the inventory + order only when the button start was pressed

### ISSUE THREAD

**Issue by frederikhegger** [rockin-robot-challenge/at_work_central_factory_hub#17]
And stop publishing inventory + order when the "reset" button was pressed

**Comment by frederikhegger** [comment]
@moriarty: I just found this issue. That's exactly what we talked about a few days ago

**Comment by moriarty** [comment]
Fixed in robocup-at-work fork

https://github.com/robocup-at-work/at_work_central_factory_hub/commit/c3c3bd4cb90f39152542f34985259639ac5a8c29
